name: PlayerBalancerAddon
main: com.jaimemartz.playerbalanceraddon.PlayerBalancerAddon
version: ${project.version}
authors: [jaime29010, BGHDDevelopment, Happy_FZM]
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
  spb:
    description: DreamCloud
    permission: hub.admin